### ISSUE TITLE
What's the pybind version required to build on Ubuntu 22.04?

### ISSUE THREAD

**Issue by nlw0** [NVIDIA/nvImageCodec#44]
### Describe the question.

I'm trying to build on Ubuntu 22.04 (Jetson_Linux_R36.4.4) but it fails because of pybind. Apparently the Ubuntu package is too old. Any recommendations about how to get it working?

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/nvImageCodec/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @nlw0,

Have you tried setting `NVIMGCODEC_BUILD_PYBIND11` to ON when running cmkae? It should build pybind11 from source.

**Comment by nlw0** [comment]
I just tried building 0.7.0 with pybind, but it's looking like the error is still there. NVIMGCODEC_BUILD_PYBIND11 is apparently already on by default. I made sure to remove any installations in the system, and I still get this error:

```
/home/user/src/nvImageCodec/python/main.cpp:57:59: error: macro "PYBIND11_MODULE" passed 3 arguments, but takes just 2
   57 | PYBIND11_MODULE(nvimgcodec_impl, m, py::mod_gil_not_used())

```

git submodule lists the pybind project as `(v2.11.0-77-g768cebe1)`, but looking at `nvImageCodec/external/pybind11/include/pybind11/detail/common.h` we can see the version defined as 1.12, and indeed the macro only takes two arguments there. There must be some confusion with the commit stored in submodules.

**Comment by nlw0** [comment]
I pulled v2.13.6 and now it builds
